services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV_DEPENDENCIES: "true"
    command: >
      sh -c "pybabel compile --directory locales &&
             alembic upgrade head &&
             exec fastapi dev main.py --host 0.0.0.0 --port 8000"
    volumes:
      - ./main.py:/app/main.py
      - ./modules:/app/modules
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finance-network

  db:
    image: postgres:18-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - finance-network

  test-db:
    image: postgres:18-alpine
    volumes:
      - dev-test-db-data:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    networks:
      - finance-network


volumes:
  dev-db-data:
  dev-test-db-data:

networks:
  finance-network:
    driver: bridge
