"""service account table

Revision ID: 0a0d7ef8dc27
Revises: 93ad34b47057
Create Date: 2026-08-17 16:04:44.379403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0a0d7ef8dc27'
down_revision: Union[str, Sequence[str], None] = '93ad34b47057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_accounts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_accounts_api_key'), 'service_accounts', ['api_key'], unique=True)
    op.create_index(op.f('ix_service_accounts_name'), 'service_accounts', ['name'], unique=True)
    op.add_column('entries', sa.Column('created_by_service_account_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'entries', 'service_accounts', ['created_by_service_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'created_by_service_account_id')
    op.drop_index(op.f('ix_service_accounts_name'), table_name='service_accounts')
    op.drop_index(op.f('ix_service_accounts_api_key'), table_name='service_accounts')
    op.drop_table('service_accounts')
    # ### end Alembic commands ###
