"""create entries

Revision ID: 93ad34b47057
Revises: 266848a9adbf
Create Date: 2026-07-16 15:16:52.425490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ad34b47057'
down_revision: Union[str, Sequence[str], None] = '266848a9adbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('DEBIT', 'CREDIT', name='entrytype'), nullable=False),
    sa.Column('payment_method', sa.Enum('DEBIT_CARD', 'CREDIT_CARD', 'PIX', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('payment_date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=125), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_fixed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        nullable=True,
    ),
    sa.Column(
        "deleted_at",
        sa.DateTime(timezone=True),
        nullable=True,
    ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_table('entries')
    # ### end Alembic commands ###
